### ISSUE TITLE
Resource Server

### ISSUE THREAD

**Issue by paultofunmi** [gigsterous/auth-server#5]
This is not an issue per say. May I gently request for a resource server or links to resource server written in spring boot. Lastly, what should be added to make it production ready?

**Comment by Smedzlatko** [comment]
Hi Paultofunmi,

I happen to have a resource server which uses a fork of this particular auth server. Take a look at [this repository](https://github.com/Withergate/api).

As for making the auth server production ready, the main thing that should be done is hooking it to a real standalone database instead of in-memory H2 DB which is there at the moment. If you have a database running, you can simply change the `application.properties` to connect to it or inject the sensitive data through environmental variables.
